### PR TITLE
Update publishing-web-apps.md

### PR DESCRIPTION
**Pull request by Ahmed-Aghadi**
fixed markdown syntax for the preview.

### CODE REVIEW

**Comment by awantoch** [comment]
thank you so much for your contribution! unfortunately it does look like this breaks the GitBook formatting -- anywhere there is a `{%` character is a special GitBook embed that allows us to do the tab views and such.

However, this does bring the point of whether the tab views are optimal -- since we can't link to them directly it might actually be better if we change those to become h3's like `### Option 1: Web Dashboard`

This would enable us to scroll through the options, see them in the table of contents in the sidebar, and link to them directly in URLs. How does that sound?

thanks so much again!

**Comment by Ahmed-Aghadi** [comment]
In GitHub, it shows the `{%` as it is in .md files which breaks the formatting as GitHub doesn't consider `{%` as special character. We can replace `{% tab title="Next.js" %}` with `#### Next.js` but what about `{% hint style="warning" %}` and other similar embed?

**Comment by awantoch** [comment]
> In GitHub, it shows the `{%` as it is in .md files which breaks the formatting as GitHub doesn't consider `{%` as special character. We can replace `{% tab title="Next.js" %}` with `#### Next.js` but what about `{% hint style="warning" %}` and other similar embed?

Ideally we can keep those, so that it renders as a warning block as shown here: https://docs.valist.io/publishing/publishing-web-apps

But we can definitely change the tabs to separate headers! 😄

**Comment by Ahmed-Aghadi** [comment]
> Ideally we can keep those, so that it renders as a warning block as shown here: https://docs.valist.io/publishing/publishing-web-apps

But what about GitHub .md files? Is it okay as GitHub doesn't format `{%`?

**Comment by awantoch** [comment]
> > Ideally we can keep those, so that it renders as a warning block as shown here: https://docs.valist.io/publishing/publishing-web-apps
> 
> But what about GitHub .md files? Is it okay as GitHub doesn't format `{%`?

Since we use the docs.valist.io GitBook as the main entrypoint it's okay that it's not perfectly formatted in GitHub :)

**Comment by Ahmed-Aghadi** [comment]
Okay! So I changed `{% tab title="xyz" %}` to `### xyz`. Is it okay?

**Pull request closed without merging**
